### ISSUE TITLE
Voyager 1.0.7 validation errors doesn't show

### ISSUE THREAD

**Issue by acalic** [thedevdojo/voyager#2236]
- Laravel Version: 5.4.36
- Voyager Version: 1.0.7
- PHP Version: 5.6.28
- Database Driver & Version:

### Description:
BREAD Validation errors stopped showing after updating voyager. Instead of showing the validation errors of a BREAD in related edit-add page, it shows JS console errors (app.js). I don't remember which was the voyager version number while it still worked, but it was working before. Now the validations just don't work, or they just don't show up right.

Validation example for field "Title" of "Post" BREAD:
```
{
    "validation": {
        "rule": "required|alpha|max:6"
    }
}
```

![voyager-error-js](https://user-images.githubusercontent.com/33701348/32857828-81badc3a-ca49-11e7-82bd-4caf490b943d.PNG)
![voyager-error-net-response](https://user-images.githubusercontent.com/33701348/32857829-81e700ee-ca49-11e7-8388-75c93e88a391.PNG)

### Steps To Reproduce:
Add validation options in BREAD editor, open and try to edit that BREAD, click on "Save" button.

**Comment by Victor-emil** [comment]
I did some research and the bug was introduced in 1.06. The "name" attribute of all formfields has been renamed "data-name". The Javascript to handle this has also been altered to take care of the renaming. However, the edit-add.blade.php file inside posts does not reflect this change. The attribute is still called name, which means that the Javascript tries to retrieve a value from an attribute that does not exist due to the name mismatch.

**Comment by acalic** [comment]
@Victor-emil This happens for all my BREADs, i used the "Post" model just as an example. Thanks for trying to help though.

**Comment by Victor-emil** [comment]
@acalic. I see. I thought that was the only point of failure, but you were totally right. It happens everywhere. I found a bug somewhere else, though. In release 1.06 the ajax calls for validation returns the display_name instead of the actual field name (If an error occurs). The Javascript code will use the display name to find the correct field, however the field name and field/model display name are usually not the same. 
If you go to Edit Bread on the posts table and change the Title to title it will work, but that is not a sustainable solution. That is a temporarily fix, but the Javascript/php code should be changed. If I get the time I will try to do a PR.
Personally I think the code should be using the id of the dom element (id="title" etc.) instead of the name for fetching.

**Comment by rttolipas** [comment]
Thank you for working this out @Victor-emil!

**Comment by fletch3555** [comment]
The reason we use the name field is because it's the field that forms use as keys when submitted.  We had an issue recently where a PR made changes to what field was used, changing it to "display name" for the purposes of fixing some i18n issue.  We have since reverted that change and implemented a better one.  I'm not saying it's perfect right now, but it should be a lot more consistent.  Apologies to anyone that got caught in the middle of that.  We've implemented stricter QA policies around PRs that should help prevent this from recurring

**Comment by ratt** [comment]
This is still an issue on the dev-master branch

**Comment by hirwaf** [comment]
This still an issue ...

**Comment by shahbaz-dev1** [comment]
I am having the same issue even I pulled the package 2 days ago. The issue is not fixed yet.

**Comment by regiszanandrea** [comment]
The issue is not fixed yet. We need a solution.

**Comment by fletch3555** [comment]
We're aware it's not fixed yet. If it were, the issue would be closed.  You're welcome to fix it and submit a PR, or be patient and we'll update the issue once fixed

**Comment by regiszanandrea** [comment]
@fletch3555 https://github.com/the-control-group/voyager/pull/2612

**Comment by emptynick** [comment]
This was also fixed in #2660
