### ISSUE TITLE
Problem with BREAD form when multilingual is enabled

### ISSUE THREAD

**Issue by Terixer** [thedevdojo/voyager#2894]
- Laravel Version: 5.5.39
- Voyager Version: 1.0.16
- PHP Version: 7.2.3
- Database Driver & Version: MySql  5.7.21
- Browser: Google Chrome

### Steps To Reproduce:
1. Make my own model of Page
2. Delete "title" from `$translatable` array
3. In edit Page in database check "Not null" for title
3. Enable multilingual
4. Go to adding page.
5. Fill everything in all languages. 
6. Button "Save" doesn't do anything, but in console I see error `An invalid form control with name='body' is not focusable`

**Comment by emptynick** [comment]
Take a look at those 2 issues: https://github.com/the-control-group/voyager/issues/2578 and https://github.com/the-control-group/voyager/issues/2288
Its either fixed in `1.0.16` (republish assets with `--force` flag) and/or was a bug in Chrome

**Comment by Terixer** [comment]
@emptynick Thanks for help :+1:

**Comment by emptynick** [comment]
You got it working?

**Comment by piratadelfuturo** [comment]
Laravel Version: 5.5.40
Voyager Version: 1.0.17
PHP Version: 7.2.3
Database Driver & Version: MySql 5.7.20
Browser: Google Chrome 65, Safari 11.1 

When I setup multilingual I get the same error described.

I republished the assets with `--force` and it is still showing the `An invalid form control with name='body' is not focusable` error, what else can be done?

**Comment by fletch3555** [comment]
You can't use `required` validation with Voyager multilingual functionality currently.  When you do so, Laravel adds browser-native validation attributes, which makes the browser try to focus the field when its contents are invalid.  Multilingual functionality adds hidden duplicate-named fields on the page for each language.  Since the fields are hidden, you can't set a value, and the browser can't focus it, it shows the above error.  This is a known issue that requires a complete rewrite of how we do i18n, so it likely won't be fixed anytime too soon.
