### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by ghost** [thedevdojo/voyager#4555]
## Version information
 - Laravel: v6.5
 - Voyager: v1.3.0
 - PHP: 7.3.10
 - Database: MariaDB 10.3.17

## Description
When running `artisan voyager:install` command, an error message is displayed: `Unable to locate publishable resources`

## Steps To Reproduce
1. `composer create-project laravel/laravel test`
2. `cd test && composer require tcg/voyager`
3. `php artisan voyager:install`

## Expected behavior
No error

## Additional context

The error occurs when trying to publish Intervention/Image service provider. The script tries to publish the `ImageServiceProviderLaravel5` class which does not exist (anymore, probably). It should publish `ImageServiceProviderLaravelRecent` instead.

## Workaround

After install, run: 
```
artisan vendor:publish --provider Intervention\Image\ImageServiceProviderLaravelRecent
```

Which will produce:
```
Copied File [/vendor/intervention/image/src/config/config.php] To [/config/image.php]
Publishing complete.
Publishing complete.
```

**Comment by danangs57** [comment]
Unable to locate publishable resources.

**Comment by princephpdev** [comment]
Did anyone got the solution ? Because after this , Voyager works fine except when open the database menu. It says missing required param -> route -> bread.delete.index ... something wrong in voyager tools->database->index.blade.php

**Comment by ghost** [comment]
@princephpdev I'm pretty sure I've proposed a workaround...
The installation process goes well, except publishable files which are not published. Just publish them and it's all fine.
The problem you have is not related to this specific issue.

**Comment by IvAndrew** [comment]
> after this , Voyager works fine except when open the database menu. It says missing required param -> route -> bread.delete.index

This is another bug - #4586 and that have been fixed

**Comment by princephpdev** [comment]
Thanks to all it is working now

**Comment by cetricokola** [comment]
php artisan vendor:publish --provider "Intervention\Image\ImageServiceProviderLaravelRecent"
instead of 
artisan vendor:publish --provider Intervention\Image\ImageServiceProviderLaravelRecent

**Comment by sushmeshrestha** [comment]
php artisan vendor:publish --provider="Backpack\CRUD\CrudServiceProvider" --tag="public"

**Unable to locate publishable resources.**
_Publishing complete._
 Still cannot fix this issue .

**Comment by MrCrayon** [comment]
@sushmeshrestha that package has nothing to do with Voyager, it's another Admin Package.
