### ISSUE TITLE
Route [voyager.dashboard] not defined.

### ISSUE THREAD

**Issue by ahmedonee** [thedevdojo/voyager#506]
- Laravel Version: 5.3
- Voyager Version: the latest
- PHP Version: 7

**Comment by marktopper** [comment]
Did you run the `php artisan voyager:install` command?

**Comment by ahmedonee** [comment]
yes i did

**Comment by marktopper** [comment]
What does your `routes/web.php` file looks like?

**Comment by ahmedonee** [comment]
it was solved , thank you

**Comment by jnanin** [comment]
Hi there,

Same issue here with Laravel 5.4 doing a new site installation + voyager installation following the readme instructions. Steps to reproduce:

```
laravel new sitename
composer require tcg/voyager
php artisan voyager:install --with-dummy
```

Last command generates the error below
```
...
Migrated: 2017_01_15_000000_make_table_name_nullable_in_permissions_table
Dumping the autoloaded files and reloading all new files
Adding Voyager routes to routes/web.php
Seeding data into the database
                                          
  [InvalidArgumentException]              
  Route [voyager.dashboard] not defined.  
```

The `routes/web.php` has the following routes:

```
Route::get('/', function () {
    return view('welcome');
});


Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```

Admin page is accessible, but I cannot login because the users table has no dummy data

Edit: I relaunched `php artisan voyager:install --with-dummy` and it now managed to seed the db with the dummy data.

**Comment by marktopper** [comment]
So your issue was only happening the first time it tried to run the installation?

**Comment by jnanin** [comment]
Yes, I re-run the installation command and it managed to seed the db, without modifying anything in between both runs

**Comment by abdgad** [comment]
@marktopper I think the issue is that Voyager during installation adds the routes to `/routes/web.php`, but when `MenuItemsTableSeeder` tries to access the route, it's still not loaded until the next time Laravel boots up.

**Comment by marktopper** [comment]
I think we should reload the `routes/web.php` file when the routes have been published.

**Comment by ShamarKellman** [comment]
I had this same issue, but it was an existing installation and I was seeding a custom Data type.  I get the error on the first run but not on the second run.

**Comment by etconsilium** [comment]
@marktopper 
add pls `\Route::group(['prefix' => 'admin'], function () {\Voyager::routes();});` to line 82 InstallCommand.php to solve problem. 
because route `voyager` must be load.
thnx

**Comment by marktopper** [comment]
@etconsilium: Mind sending a pull request?

**Comment by etconsilium** [comment]
@marktopper 
https://github.com/the-control-group/voyager/pull/1155

**Comment by marktopper** [comment]
Thanks @etconsilium

**Comment by tranpuil** [comment]
I get the following error when run my laravel project.

(3/3) ErrorException
Route [custom.profiles] not defined. (View: C:\xampp\htdocs\PaxGms\resources\views\layouts\app.blade.php) (View: C:\xampp\htdocs\PaxGms\resources\views\layouts\app.blade.php)

these are my routes

Route::get('/', function () {
    return view('welcome');
});
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('admin/home', 'AdminController@index')->name('admin.home');

Route::get('admin', 'Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login');
Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset', 'Admin\ResetPasswordController@reset');
Route::get('admin-password/reset/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::get('custom/profiles', 'UserController@index');

this is UserController

namespace App\Http\Controllers;

//use Illuminate\Http\Request;
use Auth;
class UserController extends Controller
{
    public function profile()
    {
        return view('custom.profiles', array('user' => Auth::user()));
    }
}

html

 <a href="{{ route('custom.profiles') }}">                                            
     <i class="fa fa-btn fa-user">Profile</i> 
</a>

Please any help?
Thanks in advance!

**Comment by marktopper** [comment]
@tranpuil, please make sure that this line is added to the `routes/web.php` file:

```
Route::group(['prefix' => 'admin'], function () {
    Voyager::routes();
});
```

**Comment by fletch3555** [comment]
@tranpuil, this issues has had no activity for 3 months.  In the future, please post on slack or create your own issue.

Your issue is unrelated to Voyager, please try asking for help in a more generic laravel forum, such as on laracasts.com or in the larachat slack group.

**Comment by ezequiel9** [comment]
**Hello, Somebody can help me about GIT? How to use this admin Voyager using git? For example, If you need add new content type, how to add to git for future push and deploy in the remote server?**

**Comment by amirbg4001** [comment]
Route [voyager.dashboard] not defined

I am having this issue on a website which was just working for 5 months and all of a sudden I'm facing this please help

**Comment by fletch3555** [comment]
This issue has been closed for nearly 2 years now.  Please open your own issue instead of commenting on old issues.

Also, there's zero chance that this suddenly broke. Something absolutely did change, though maybe not consciously by you.  Please make sure to include ANY changes that might be related.
