### ISSUE TITLE
Error installation on Laravel 8

### ISSUE THREAD

**Issue by scaffarelli** [thedevdojo/voyager#5391]
## Version information
 - Laravel: v8.0
 - Voyager: v1.4
 - PHP: 8.0.8

## Description
Error trying to install Voyager.

## Steps To Reproduce
1. Run the installation command **composer require tcg/voyager**
2. Then you got the error below:

Using version ^1.4 for tcg/voyager
./composer.json has been updated
Running composer update tcg/voyager
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - tcg/voyager[1.4.x-dev, ..., 1.x-dev] require intervention/image ^2.4 -> satisfiable by intervention/image[2.4.0, ..., 2.5.1].
    - intervention/image 2.4.x-dev is an alias of intervention/image dev-master and thus requires it to be installed too.
    - tcg/voyager[v1.4.0, ..., v1.4.2] require illuminate/support ~6.0|~7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - intervention/image[dev-master, 2.4.0, ..., 2.5.1] require guzzlehttp/psr7 ~1.1 -> found guzzlehttp/psr7[1.1.0, ..., 1.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires tcg/voyager ^1.4 -> satisfiable by tcg/voyager[v1.4.0, ..., 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Following the recommendation with -W**

Using version ^1.4 for tcg/voyager
./composer.json has been updated
Running composer update tcg/voyager --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires laravel/framework ^8.40, found laravel/framework[v8.40.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

## Expected behavior
Be able to successfully install Voyager

## Screenshots
<img width="1196" alt="Captura de Pantalla 2021-07-02 a la(s) 17 45 52" src="https://user-images.githubusercontent.com/30665842/124299159-6782d100-db5d-11eb-987a-065f754633ab.png">

**Comment by Kylpilion** [comment]
same

**Comment by sarjo** [comment]
same

**Comment by grzegorz-rozycki** [comment]
IMO it's because Laravel has a dev dependency on `"doctrine/dbal": "^2.6|^3.0",` and if you've locked the version at `^3.0` you get this conflict. As a workaround try to downgrade `doctrine/dbal` to ^2.6

**Comment by pritam3010** [comment]
Facing the same issue.

**Comment by pritam3010** [comment]
> Facing the same issue.

This issue is happening as  Voyager requires ` intervention/image` package which depends on `guzzlehttp/psr7 [ < 2.0.0]`.
 I ran the command `composer require intervention/image -W` which in turn downgrades the` guzzlehttp/psr7 from 2.0.0 => 1.8.2`. 

After that, I try to install Voyager and it installed successfully.

I don't know by downgrading  `guzzlehttp/psr7` will face issues elsewhere. If anyone knows please let us know.

**Comment by BuddhiEash** [comment]
Experiencing the same issue. I downgraded to Laravel version 7 and tried. But getting the same issue.

**Comment by pritam3010** [comment]
@BuddhiEash  Run the `composer require intervention/image -W` in the project directory, after that you can install Voyager for laravel 8.
You can see my previous comment for the detail.

**Comment by BuddhiEash** [comment]
@pritam3010 Thanks for the reply. I like to try that, but my concern is whether it will cause to occur any other issue with other dependencies.

**Comment by pritam3010** [comment]
Faced issue in installing `voyager-redirects` hook using voyager admin panel.


```
RuntimeException
require.voyager-redirects is invalid, it should have a vendor name, a forward slash, and a package name. 
The vendor and package name can be words separated by -, . or _. 
The complete name should match "^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]?|-{0,2})[a-z0-9]+)*$".
```

I don't know that this error is thrown due to the changes made during installation  (mentioned in the above comment) on any other issue.

**Comment by cfpinto** [comment]
if you're ok with deleting composer.lock (not recommended in most cases) you might get away with it. btw my understanding is that for Laravel 8 you need Voyager 1.4.x-dev which is a dev release. you might find a few nagging things like this

**Comment by whyiscaothu** [comment]
composer require tcg/voyager --no-update
composer install
composer update

work for me. I'm use laravel 8.40

**Comment by emptynick** [comment]
Unfortunately we have to find a replacement for `intervention/image` as it seems to be abandoned. Might take a little while.

Edit: good timing, things are moving over at intervention. We'll see what happens the next day(s)

**Comment by jefferdo** [comment]
> composer update

THis works. Thanks

**Comment by jefferdo** [comment]
> composer require tcg/voyager --no-update
> composer install
> composer update
> 
> work for me. I'm use laravel 8.40

This works. Thanks

**Comment by BuddhiEash** [comment]
It seems the issue is fixed now.

Just executed the normal voyager installation command.

`composer require tcg/voyager`

Tested with Laravel Framework 8.49.2 and Laravel Framework 8.50.0

And it works without an issue.

Thanks!

**Comment by cjsfj** [comment]
Seems like this works with dev only. Will we get a 1.4.x release anytime that has this support?

**Comment by itsrafsanjani** [comment]
**Solved:** Require `"tcg/voyager": "^1.4.3"` to your `composer.json` and run `composer update`.
This works for me!

My problem was:
```sh
  Problem 1
    - tcg/voyager[v1.4.3, ..., 1.x-dev] require doctrine/dbal ^2.5 -> found doctrine/dbal[v2.5.0-BETA2, ..., 2.13.x-dev] but the package is fixed to 3.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - tcg/voyager[v1.4.0, ..., v1.4.2] require illuminate/support ~6.0|~7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires tcg/voyager ^1.4 -> satisfiable by tcg/voyager[v1.4.0, ..., 1.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

**Comment by ghost** [comment]
Any reason the constraint hasn't been updated yet? It's holding back upgrades on my projects.

I managed to instal it with the `--no-update` tag but that feels like a dirty workaround :-)

**Comment by rambhosale** [comment]
Any update on this issue still facing the same error
Any reason for not upgrading the ```doctrine/dbal``` library to the latest version?
